### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by marcusloren** [lannng/react-admin-dashboard#1]
is experiencing an error while running in the terminal

**Failed to compile.

./src/containers/App.js
Module not found: Can't resolve '../config' in '/Users/marcus/react-admin-dashboard/src/containers'**

**Comment by lannify** [comment]
This gitignored config file contains firebase credentials. You need to provide this file with your own firebase credentials.

**Comment by saddam1997** [comment]
Hi @lannify  ,

Please provide sample of conf file with parameter !!!

**Comment by lannify** [comment]
Added config files with mock Firebase credentials.
